# Generated by Django 3.0.7 on 2020-06-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Donor Address'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='birthdate',
            field=models.DateField(verbose_name='Donor Birthdate'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(verbose_name='Donor Name'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Donor Email'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.IntegerField(verbose_name='Donor Gender'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='is_banned',
            field=models.IntegerField(verbose_name='Banned!'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Donor Name'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Donor Password'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Donor Phone Number'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Donor Username'),
        ),
    ]
