# Generated by Django 3.0.7 on 2020-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Charity Name')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('logo', models.TextField()),
                ('description', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('is_banned', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'charity',
                'verbose_name_plural': 'charities',
                'db_table': 'charity',
                'managed': True,
            },
        ),
    ]
