# Generated by Django 3.0.7 on 2020-06-12 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Charity Address'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Charity City'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='description',
            field=models.TextField(verbose_name='Charity Description'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Charity Email'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='is_banned',
            field=models.IntegerField(verbose_name='Banned! '),
        ),
        migrations.AlterField(
            model_name='charity',
            name='logo',
            field=models.ImageField(upload_to='charity/', verbose_name='Charity Logo'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Charity Password'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Charity Phone Number'),
        ),
    ]
