# Generated by Django 3.0.7 on 2020-06-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('needed_amount', models.IntegerField()),
                ('approved', models.IntegerField()),
                ('ben', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.Beneficiary')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'db_table': 'cases',
                'managed': True,
            },
        ),
    ]
