# Generated by Django 3.0.7 on 2020-06-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_auto_20200612_0806'),
        ('subcategory', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcategory.Subcategory'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='ben',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beneficiary.Beneficiary'),
        ),
    ]
