# Generated by Django 3.0.7 on 2020-06-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory', '0001_initial'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryFeatures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Features')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.Subcategory')),
            ],
            options={
                'verbose_name': 'SubcategoryFeature',
                'verbose_name_plural': 'SubcategoryFeatures',
                'db_table': 'subcategory_features',
                'managed': True,
            },
        ),
    ]
