from django.urls import path
from . import views

app_name='category'

urlpatterns = [
    path('category/',views.all_programs, name='all_programs'),
    path('category/development/',views.development, name='development'),
    path('category/economic_support',views.economic_support, name='economic_support'),
    path('category/medical',views.medical , name='medical'),
    path('category/social_support',views.social_support, name='social_support'),
    path('category/zakat',views.zakat, name='zakat'),
    path('category/medical/addiction',views.addiction, name='addiction'),
    path('category/medical/tumor',views.tumor, name='tumor'),
    path('category/medical/babies',views.baby, name='baby'),
    path('category/social_support/blind',views.blind, name='blind'),
    path('category/medical/accident_burns',views.accident_burns, name='accident_burns'),
    path('category/medical/virus_c',views.virus_c, name='virus_c'),
    path('category/medical/cancer',views.cancer, name='cancer'),
    path('category/medical/heart',views.heart, name='heart'),
    path('category/medical/kidny',views.kidny, name='kidny'),
    path('category/medical/ray',views.ray, name='ray'),
    path('category/medical/special_people',views.special_people, name='special_people'),
    path('category/medical/surgery',views.surgery, name='surgery'),
    path('category/medical/treatment',views.treatment, name='treatment'),
    path('category/medical/artificial_limps',views.artificial_limps, name='artificial_limps'),
    path('category/social_support/children',views.children, name='children'),
    path('category/medical/blind_diseas',views.blind_diseas,name='blind_diseas'),
    path('category/social_support/food',views.food, name='food'),
    path('category/social_support/deptors',views.deptors, name='deptors'),
    path('category/social_support/old_people',views.old_people ,name='old_people'),
    path('category/social_support/clothes',views.clothes , name='clothes'),
    path('category/social_support/orphans_marriage',views.orphans_marriage , name='orphans_marriage'),
    path('category/social_support/orphans',views.orphans , name='orphans'),
    path('category/economic_support/cow',views.cow , name='cow'),
    path('category/economic_support/good_loan',views.good_loan , name='good_loan'),
    path('category/economic_support/jop',views.jop ,name='jop'),
    path('category/economic_support/charity_project',views.charity_project ,name='charity_project'),
    path('category/development/water',views.water , name='water'),
    path('category/development/house',views.house ,name='house'),
    path('category/zakat/trade',views.trade , name='trade'),
    path('category/zakat/silver_zakat',views.silver_zakat ,name='silver_zakat'),
    path('category/zakat/gold_zakat',views.gold_zakat , name='gold_zakat'),
    path('category/zakat/fetr',views.fetr , name='fetr'),
    path('category/zakat/rekaz',views.rekaz , name='rekaz'),
    path('category/zakat/out-of-land',views.out_of_land ,name='out_of_land'),
    path('category/zakat/land',views.land ,name='land'),
    path('category/zakat/Money_zakat',views.Money_zakat , name='Money_zakat'),
]
