# Generated by Django 3.0.7 on 2020-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'features',
                'verbose_name_plural': 'features',
                'db_table': 'features',
                'managed': True,
            },
        ),
    ]
