# Generated by Django 3.0.7 on 2020-06-09 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('national_id', models.BigIntegerField(unique=True)),
                ('gender', models.IntegerField()),
                ('martial_status', models.CharField(max_length=8, verbose_name='beneficiary status')),
                ('name', models.CharField(max_length=255, verbose_name='beneficiary name')),
                ('address', models.CharField(max_length=255, verbose_name='beneficiary address')),
                ('city', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('photo', models.ImageField(upload_to='beneficiary/')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.Charity')),
            ],
            options={
                'verbose_name': 'beneficiary',
                'verbose_name_plural': 'beneficiaries',
                'db_table': 'beneficiary',
                'managed': True,
            },
        ),
    ]
