# Generated by Django 3.0.7 on 2020-06-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20200612_0806'),
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charity.Charity'),
        ),
    ]
