from django.urls import path
from . import views


urlpatterns = [
    path('programs/',views.all_programs),
    path('programs/development',views.development),
    path('programs/economic_support',views.economic_support),
    path('programs/medical',views.medical),
    path('programs/social_support',views.social_support),
    path('programs/zakat',views.zakat),
    path('programs/medical/addiction',views.addiction),
    path('programs/medical/tumor',views.tumor),
    path('programs/medical/babies',views.baby),
    path('programs/medical/blind',views.blind),
    path('programs/medical/accident_burns',views.accident_burns),
    path('programs/medical/virus_c',views.virus_c),
    path('programs/medical/cancer',views.cancer),
    path('programs/medical/heart',views.heart),
    path('programs/medical/kidny',views.kidny),
    path('programs/medical/ray',views.ray),
    path('programs/medical/special_people',views.special_people),
    path('programs/medical/surgery',views.surgery),
    path('programs/medical/treatment',views.treatment),
    path('programs/medical/artificial_limps',views.artificial_limps),
    path('programs/social_support/children',views.children),
    path('programs/social_support/blind',views.blind),
    path('programs/social_support/blind_diseas',views.blind_diseas),
    path('programs/social_support/food',views.food),
    path('programs/social_support/deptors',views.deptors),
    path('programs/social_support/old_people',views.old_people),
    path('programs/social_support/clothes',views.clothes),
    path('programs/social_support/orphans_marriage',views.orphans_marriage),
    path('programs/social_support/orphans',views.orphans),
    path('programs/economic_support/cow',views.cow),
    path('programs/economic_support/good_loan',views.good_loan),
    path('programs/economic_support/jop',views.jop),
    path('programs/economic_support/charity_project',views.charity_project),
    path('programs/development/water',views.water),
    path('programs/development/house',views.house),
    path('programs/zakat/trade',views.trade),
    path('programs/zakat/silver_zakat',views.silver_zakat),
    path('programs/zakat/gold_zakat',views.gold_zakat),
    path('programs/zakat/fetr',views.fetr),
    path('programs/zakat/rekaz',views.rekaz),
    path('programs/zakat/out-of-land',views.out_of_land),
    path('programs/zakat/land',views.land),
    path('programs/zakat/Money_zakat',views.Money_zakat),

]
